---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-auth0
  namespace: oauth2-proxy
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: oauth2-proxy-auth0
    creationPolicy: Owner
  data:
    - secretKey: domain
      remoteRef:
        key: oauth2-proxy-auth0/credentials/domain
    - secretKey: client_id
      remoteRef:
        key: oauth2-proxy-auth0/credentials/client_id
    - secretKey: client_secret
      remoteRef:
        key: oauth2-proxy-auth0/credentials/client_secret
    - secretKey: cookie_secret
      remoteRef:
        key: oauth2-proxy-auth0/credentials/cookie_secret
