---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: betterstack-otel
  namespace: otel-collector
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: betterstack-otel
    creationPolicy: Owner
  data:
    - secretKey: sourceToken
      remoteRef:
        key: betterstack-otel/credentials/source_token
    - secretKey: ingestingHost
      remoteRef:
        key: betterstack-otel/credentials/ingesting_host
