locals {
  # Schematic ID for the public Talos image provided by Hetzner Cloud (Talos + qemu-guest-agent).
  # Available as a public Hetzner image since 2025-04-23; minor patch updates are managed by Hetzner.
  # https://factory.talos.dev/?schematic=ce4c980550dd2ab1b17bbf2b08801c7eb59418eafe8f279833297925d67c7515
  talos_schematic = "ce4c980550dd2ab1b17bbf2b08801c7eb59418eafe8f279833297925d67c7515"

  # Explicit IP assignments. Counts are derived from list length to prevent drift.
  control_plane_ips = ["10.0.1.1", "10.0.1.2"]
  worker_ips        = ["10.0.1.11", "10.0.1.12"]
}

# Resolve the public Talos image provided by Hetzner Cloud using the schematic ID.
# No manual snapshot upload required.
data "hcloud_image" "talos" {
  name              = local.talos_schematic
  with_architecture = "x86"
}

# Private network for intra-cluster traffic
resource "hcloud_network" "main" {
  name     = "willpxxr-prod"
  ip_range = "10.0.0.0/16"
}

resource "hcloud_network_subnet" "main" {
  network_id   = hcloud_network.main.id
  type         = "cloud"
  network_zone = "eu-central"
  ip_range     = "10.0.1.0/24"
}

# Load balancer for the Kubernetes API — provides a stable endpoint across control plane nodes
resource "hcloud_load_balancer" "control_plane" {
  name               = "willpxxr-prod-cp"
  load_balancer_type = "lb11"
  location           = "nbg1"
}

resource "hcloud_load_balancer_network" "control_plane" {
  load_balancer_id = hcloud_load_balancer.control_plane.id
  network_id       = hcloud_network.main.id
  ip               = "10.0.1.254"

  depends_on = [hcloud_network_subnet.main]
}

resource "hcloud_load_balancer_service" "kube_api" {
  load_balancer_id = hcloud_load_balancer.control_plane.id
  protocol         = "tcp"
  listen_port      = 6443
  destination_port = 6443
}

resource "hcloud_load_balancer_target" "control_plane" {
  count            = length(local.control_plane_ips)
  type             = "server"
  load_balancer_id = hcloud_load_balancer.control_plane.id
  server_id        = hcloud_server.control_plane[count.index].id
  use_private_ip   = true

  depends_on = [hcloud_load_balancer_network.control_plane]
}

# Talos PKI and secrets — generated once, stored in Terraform state
resource "talos_machine_secrets" "main" {}

# Control plane machine configuration
data "talos_machine_configuration" "control_plane" {
  cluster_name     = "willpxxr-prod"
  machine_type     = "controlplane"
  cluster_endpoint = "https://${hcloud_load_balancer.control_plane.ipv4}:6443"
  machine_secrets  = talos_machine_secrets.main.machine_secrets
}

# Worker machine configuration
data "talos_machine_configuration" "worker" {
  cluster_name     = "willpxxr-prod"
  machine_type     = "worker"
  cluster_endpoint = "https://${hcloud_load_balancer.control_plane.ipv4}:6443"
  machine_secrets  = talos_machine_secrets.main.machine_secrets
}

# CX22: 2 vCPU, 4 GB RAM, 40 GB NVMe — dedicated control plane nodes.
# Note: a 2-member etcd cluster requires both nodes for write quorum; losing either
# member makes the cluster read-only. Add a third control plane for true fault tolerance.
# Security: the Kubernetes API is protected by TLS + RBAC; the Talos API is protected
# by mTLS (certificates generated by talos_machine_secrets). No IP-based firewall is
# used because: (a) it would not cover the load balancer's public IP, and (b) it would
# prevent Terraform Cloud remote runs from reaching the Talos API during bootstrap.
resource "hcloud_server" "control_plane" {
  count       = length(local.control_plane_ips)
  name        = "willpxxr-prod-cp-${count.index + 1}"
  server_type = "cx22"
  location    = "nbg1"
  image       = data.hcloud_image.talos.id

  network {
    network_id = hcloud_network.main.id
    ip         = local.control_plane_ips[count.index]
  }

  depends_on = [hcloud_network_subnet.main]
}

# CX22: 2 vCPU, 4 GB RAM, 40 GB NVMe — dedicated worker nodes.
resource "hcloud_server" "worker" {
  count       = length(local.worker_ips)
  name        = "willpxxr-prod-worker-${count.index + 1}"
  server_type = "cx22"
  location    = "nbg1"
  image       = data.hcloud_image.talos.id

  network {
    network_id = hcloud_network.main.id
    ip         = local.worker_ips[count.index]
  }

  depends_on = [hcloud_network_subnet.main]
}

# Push the Talos machine config to each control plane node
resource "talos_machine_configuration_apply" "control_plane" {
  count                       = length(local.control_plane_ips)
  client_configuration        = talos_machine_secrets.main.client_configuration
  machine_configuration_input = data.talos_machine_configuration.control_plane.machine_configuration
  node                        = hcloud_server.control_plane[count.index].ipv4_address

  depends_on = [hcloud_server.control_plane]
}

# Push the Talos machine config to each worker node
resource "talos_machine_configuration_apply" "worker" {
  count                       = length(local.worker_ips)
  client_configuration        = talos_machine_secrets.main.client_configuration
  machine_configuration_input = data.talos_machine_configuration.worker.machine_configuration
  node                        = hcloud_server.worker[count.index].ipv4_address

  depends_on = [hcloud_server.worker, talos_machine_configuration_apply.control_plane]
}

# Bootstrap the Talos cluster on the first control plane (runs etcd, issues PKI certs)
resource "talos_machine_bootstrap" "main" {
  node                 = hcloud_server.control_plane[0].ipv4_address
  client_configuration = talos_machine_secrets.main.client_configuration

  depends_on = [talos_machine_configuration_apply.control_plane]
}

# Retrieve kubeconfig once the cluster is bootstrapped
data "talos_cluster_kubeconfig" "main" {
  client_configuration = talos_machine_secrets.main.client_configuration
  node                 = hcloud_server.control_plane[0].ipv4_address

  depends_on = [talos_machine_bootstrap.main]
}

# Expose the kubeconfig so operators can retrieve it with:
#   terraform output -raw kubeconfig > ~/.kube/willpxxr-prod.yaml
output "kubeconfig" {
  description = "Kubeconfig for the willpxxr-prod Talos cluster"
  value       = data.talos_cluster_kubeconfig.main.kubeconfig_raw
  sensitive   = true
}
