apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- flux-instance.yaml
- charts.yaml
- network-policy.yaml
- kustomization-policy.yaml
- kustomization-cert-manager.yaml
- kustomization-tailscale-operator.yaml
- kustomization-external-secrets.yaml
- kustomization-kube-system.yaml
- kustomization-external-secrets-secretstore.yaml
- kustomization-tailscale-operator-secret.yaml
- kustomization-flux-operator-route.yaml
- kustomization-envoy-gateway.yaml
- kustomization-envoy-gateway-config.yaml
- kustomization-gateway.yaml
- kustomization-cel-admission-policies.yaml
- kustomization-cel-admission-policies-config.yaml
- kustomization-envoy-ai-gateway.yaml
- kustomization-ai-gateway-llm.yaml
