apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- flux-instance.yaml
- charts.yaml
- network-policy.yaml
- gateway-api-sync.yaml
- gateway-api-kustomization.yaml
- kustomization-policy.yaml
- kustomization-cert-manager.yaml
- kustomization-tailscale-operator.yaml
- kustomization-external-secrets.yaml
- kustomization-kube-system.yaml
- kustomization-external-secrets-secretstore.yaml
- kustomization-tailscale-operator-secret.yaml
- kustomization-traefik.yaml
- kustomization-traefik-gateway.yaml
- kustomization-flux-operator-route.yaml
- kustomization-oauth2-proxy.yaml
- kustomization-envoy-gateway.yaml
- kustomization-envoy-gateway-config.yaml
