-- Run ONCE in the Supabase SQL editor as an admin (the vault role cannot
-- create itself). The password is generated by Terraform: copy the
-- `role_password` field from the mcp-token-vault item in the 1Password
-- `kubernetes` vault (written by supabase.tf), paste it below, then run.
-- The full connection string the vault consumes lives in the same item
-- (db_url) and is already assembled by Terraform.

CREATE ROLE token_vault LOGIN PASSWORD 'paste-role_password-from-1password-here';

GRANT USAGE, CREATE ON SCHEMA public TO token_vault;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO token_vault;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO token_vault;
