-- DEPRECATED: superseded by the vault's own startup bootstrap (WEP-0006):
-- the service connects with ADMIN_DATABASE_URL and reconciles the role on
-- every boot. Kept only as a manual-break-glass reference.
--
-- Run ONCE in the Supabase SQL editor as an admin (the vault role cannot
-- create itself). The password is generated by Terraform: copy the
-- `role_password` field from the mcp-token-vault item in the 1Password
-- `kubernetes` vault (written by supabase.tf), paste it below, then run.
-- The full connection string the vault consumes lives in the same item
-- (db_url) and is already assembled by Terraform.
-- Run ONCE in the Supabase SQL editor as an admin (the vault role cannot
-- create itself). Generate the password, then store the full connection
-- string in 1Password as mcp-token-vault/credentials/db_url.

CREATE ROLE token_vault LOGIN PASSWORD 'set-a-real-password-here';

GRANT USAGE ON SCHEMA public TO token_vault;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO token_vault;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO token_vault;
