---
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: traefik
  namespace: flux-system
  labels:
    fluxcd.controlplane.io/resourceset: charts
spec:
  type: Static
  defaultValues:
    name: "traefik"
    namespace: "traefik"
    repoURL: "https://traefik.github.io/charts"
    chart: "traefik"
    valuesConfigMap: "traefik-values"