ingressClass:
  enabled: false
providers:
  kubernetesGateway:
    enabled: true
gateway:
  enabled: false
gatewayClass:
  enabled: true
service:
  spec:
    type: LoadBalancer
    loadBalancerClass: tailscale
  annotations:
    tailscale.com/hostname: "gateway"
    tailscale.com/proxy-group: "ingress"
ports:
  web:
    port: 8000
    exposedPort: 80
    expose:
      default: true
  websecure:
    port: 8443
    exposedPort: 443
    expose:
      default: true