---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: operator-oauth
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: "tailscale-operator-oauth"
        property: "client_id"
    - secretKey: client_secret
      remoteRef:
        key: "tailscale-operator-oauth"
        property: "client_secret"
