---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: envoy-gateway-oidc
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: envoy-gateway-oidc
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: envoy-gateway-oidc/credentials/client_id
    - secretKey: client-secret
      remoteRef:
        key: envoy-gateway-oidc/credentials/client_secret
