---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-api
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./config/crd
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: gateway-api
  targetNamespace: default
  timeout: 3m0s
  wait: true
