---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-api-provider-cloudflared
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./config/default
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: gateway-api-provider-cloudflared
  targetNamespace: cloudflared
  timeout: 3m0s
  wait: true
