apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- flux-operator-sync.yaml
- flux-instance.yaml
- gateway-api-resourceset.yaml
- gateway-api-provider-cloudflared-resourceset.yaml
- teleport-resourceset.yaml
