apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- gateway-api-sync.yaml
- gateway-api-kustomization.yaml
- gateway-api-provider-cloudflared-kustomization.yaml
- gateway-api-provider-cloudflared-sync.yaml
- gateway-api-provider-cloudflared-components.yaml
- teleport-components.yaml
- teleport-helm-release.yaml
- teleport-helm-repository.yaml
