---
apiVersion: v1
kind: ConfigMap
metadata:
  name: teleport-values
  namespace: flux-system
data:
  values.yaml: |
    clusterName: teleport.willpxxr.com
    chartMode: standalone
    proxyListenerMode: multiplex
    acme: true
    acmeEmail: the@willpxxr.com
    publicAddr:
    - teleport.willpxxr.com:443
    authentication:
      type: github
      localAuth: true
    ingress:
      enabled: false
    service:
      type: ClusterIP
    log:
      level: INFO
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: teleport
  namespace: teleport
spec:
  parentRefs:
  - name: gateway
    namespace: cloudflared
  hostnames:
  - "teleport.willpxxr.com"
  - "*.teleport.willpxxr.com"
  rules:
    - backendRefs:
      - name: teleport-cluster
        port: 443
---
