---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: openrouter
  namespace: envoy-gateway-system
spec:
  endpoints:
    - fqdn:
        hostname: openrouter.ai
        port: 443
---
apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: openrouter-tls
  namespace: envoy-gateway-system
spec:
  targetRefs:
    - group: "gateway.envoyproxy.io"
      kind: Backend
      name: openrouter
  validation:
    wellKnownCACertificates: "System"
    hostname: openrouter.ai
