---
apiVersion: aigateway.envoyproxy.io/v1beta1
kind: BackendSecurityPolicy
metadata:
  name: openrouter-apikey
  namespace: envoy-gateway-system
spec:
  targetRefs:
    - group: aigateway.envoyproxy.io
      kind: AIServiceBackend
      name: openrouter
  type: APIKey
  apiKey:
    secretRef:
      name: openrouter
      namespace: envoy-gateway-system
