---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openrouter
  namespace: envoy-gateway-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: openrouter
    creationPolicy: Owner
  data:
    - secretKey: apiKey
      remoteRef:
        key: openrouter/credentials/api_key
