---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: ai-gateway-llm-anthropic-free
  namespace: envoy-gateway-system
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: ai-gateway-llm-anthropic-free
  jwt:
    providers:
      - name: auth0
        issuer: "https://auth.willpxxr.com/"
        remoteJWKS:
          uri: "https://auth.willpxxr.com/.well-known/jwks.json"
        audiences:
          - "https://ai.tailb40090.ts.net"
  authorization:
    defaultAction: Deny
    rules:
      - action: Allow
        principal:
          jwt:
            provider: auth0
            scopes:
              - "llm:use"
              - "llm-free:use"
