# ArgoCD app definition (see argocd/apps-applicationset.yaml + WEP-0001).
name: tailscale-operator
namespace: tailscale
helm:
  - repoURL: https://pkgs.tailscale.com/helmcharts
    chart: tailscale-operator
    version: 1.102.3
    releaseName: tailscale-tailscale-operator
    values: values.yaml
manifests:
  - network-policy.yaml
  - proxygroup.yaml
