---
apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: dnat-fallback-trial
  namespace: tailscale
spec:
  statefulSet:
    pod:
      tailscaleContainer:
        image: ghcr.io/willpxxr/tailscale:vip-svc-dnat-fallback
