---
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: otel-collector-gateway
  namespace: flux-system
  labels:
    fluxcd.controlplane.io/resourceset: charts
spec:
  type: Static
  defaultValues:
    name: "otel-collector-gateway"
    namespace: "otel-collector"
    repoURL: "https://open-telemetry.github.io/opentelemetry-helm-charts"
    chart: "opentelemetry-collector"
    valuesConfigMap: "otel-collector-gateway-values"
