---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-gateway-tls
  namespace: traefik
spec:
  secretName: traefik-gateway-tls
  duration: 8760h
  renewBefore: 720h
  issuerRef:
    name: self-signed
    kind: Issuer
  commonName: "*.tailb40090.ts.net"
  dnsNames:
    - "*.tailb40090.ts.net"