---
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: cert-manager
  namespace: flux-system
  labels:
    fluxcd.controlplane.io/resourceset: charts
spec:
  type: Static
  defaultValues:
    name: "cert-manager"
    namespace: "cert-manager"
    repoURL: "https://charts.jetstack.io"
    chart: "cert-manager"
    values:
      installCRDs: true